language: go

go:
        - 1.6

env:
        - DATE=$(date '+%s') TAG="$(echo "${TRAVIS_BRANCH}" | sed 's/-prerelease//g')-prerelease"

before_install:
        - go get github.com/mitchellh/gox
        - go get github.com/tcnksm/ghr

after_success:
        - "[ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ] && gox -ldflags \"-X 'main.buildVersion=${BUILD_VERSION} (${TRAVIS_COMMIT})' -X 'main.buildDate=${DATE}'\" -output \"dist/hoarder_{{.OS}}_{{.Arch}}\" ./cmd/hoarder || false"
        - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ghr --username tblyler --token "${GITHUB_TOKEN}" --replace --prerelease --debug "${TAG}" dist/ || false'
