language: go

go:
        - 1.6

env:
        - DATE=$(date -u '+%Y/%m/%d %H:%M:%S') BUILD_VERSION=$(if [ -n $TRAVIS_TAG ]; then echo -n $TRAVIS_COMMIT; else echo -n $TRAVIS_TAG; fi)

before_install:
        - go get github.com/mitchellh/gox
        - go get github.com/tcnksm/ghr

after_success:
        - gox -ldflags "-X 'main.buildVersion=$BUILD_VERSION' -X 'main.buildDate=$DATE'" -output "dist/ncd_{{.OS}}_{{.Arch}}" ./cmd/hoarder
        - ghr --username tblyler --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
